// src/lib/components/Header.svelte
<script>
	import { onMount } from 'svelte';

	let scrollProgress = 0;
	let headerVisible = true;
	let lastScrollY = 0;
	let isMobileMenuOpen = false;

	function toggleMobileMenu() {
		isMobileMenuOpen = !isMobileMenuOpen;
		if (isMobileMenuOpen) {
			document.body.style.overflow = 'hidden';
		} else {
			document.body.style.overflow = '';
		}
	}

	function closeMobileMenu() {
		isMobileMenuOpen = false;
		document.body.style.overflow = '';
	}

	onMount(() => {
		const updateScroll = () => {
			const winScroll = document.documentElement.scrollTop || document.body.scrollTop;
			const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
			scrollProgress = (winScroll / height) * 100;

			// Hide header on scroll down, show on scroll up
			const currentScrollY = window.scrollY;
			headerVisible = currentScrollY <= lastScrollY || currentScrollY < 100;
			lastScrollY = currentScrollY;
		};

		window.addEventListener('scroll', updateScroll);
		return () => window.removeEventListener('scroll', updateScroll);
	});
</script>

<header
	class="fixed w-full top-0 z-50 transition-transform duration-300"
	style="transform: translateY({headerVisible ? '0' : '-100%'})"
>
	<div class="glass dark:glass-dark backdrop-blur-md shadow-lg relative">
		<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
			<div class="flex justify-between items-center py-4">
				<div class="text-2xl font-bold heading">
					<span class="text-gradient">AS DATABLE</span>
				</div>
				
				<nav class="hidden sm:flex items-center space-x-8">
					<a 
						class="text-body hover:text-primary-500 dark:hover:text-primary-400 
							   transition-colors duration-300 font-medium" 
						href="#services"
					>
						Services
					</a>
					<a
						class="text-body hover:text-primary-500 dark:hover:text-primary-400
				 transition-colors duration-300 font-medium"
						href="https://www.notion.so/LLM-Stack-Diagnostic-Sprint-1be4e72a76e7808ca8ced73e87c0b211"
						target="_blank" rel="noopener noreferrer"
					>
						Sprint&nbsp;Details
					</a>
					<a 
						class="text-body hover:text-primary-500 dark:hover:text-primary-400 
							   transition-colors duration-300 font-medium" 
						href="#approach"
					>
						Approach
					</a>
					<a 
						class="text-body hover:text-primary-500 dark:hover:text-primary-400 
							   transition-colors duration-300 font-medium" 
						href="#solutions"
					>
						Solutions
					</a>
					<a 
						class="btn-primary py-2" 
						href="#contact"
					>
						Contact Us
					</a>
				</nav>

				<!-- Mobile menu button -->
				<button 
					class="sm:hidden p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
					on:click={toggleMobileMenu}
					aria-label="Toggle mobile menu"
				>
					{#if isMobileMenuOpen}
						<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
						</svg>
					{:else}
						<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
						</svg>
					{/if}
				</button>
			</div>
		</div>
	</div>

	<!-- Mobile menu -->
	{#if isMobileMenuOpen}
		<div class="absolute inset-x-0 top-full z-40 transform transition-transform duration-300">
			<div class="glass dark:glass-dark backdrop-blur-md shadow-lg">
				<nav class="flex flex-col items-center justify-center py-8 space-y-8 text-lg">
				<a 
					class="text-body hover:text-primary-500 dark:hover:text-primary-400 
						   transition-colors duration-300 font-medium" 
					href="#services"
					on:click={closeMobileMenu}
				>
					Services
				</a>
				<a
						class="text-body hover:text-primary-500 dark:hover:text-primary-400
				 transition-colors duration-300 font-medium"
						href="https://www.notion.so/LLM-Stack-Diagnostic-Sprint-1be4e72a76e7808ca8ced73e87c0b211"
						target="_blank" rel="noopener noreferrer"
						on:click={closeMobileMenu}
				>
						Sprint Details
				</a>
				<a 
					class="text-body hover:text-primary-500 dark:hover:text-primary-400 
						   transition-colors duration-300 font-medium" 
					href="#approach"
					on:click={closeMobileMenu}
				>
					Approach
				</a>
				<a 
					class="text-body hover:text-primary-500 dark:hover:text-primary-400 
						   transition-colors duration-300 font-medium" 
					href="#solutions"
					on:click={closeMobileMenu}
				>
					Solutions
				</a>
				<a 
					class="btn-primary" 
					href="#contact"
					on:click={closeMobileMenu}
				>
					Contact Us
				</a>
				</nav>
			</div>
		</div>
	{/if}

	<!-- Scroll Progress Indicator -->
	<div 
		class="scroll-indicator"
		style="width: {scrollProgress}%"
	></div>
</header>

<!-- Add spacing to prevent content from hiding under fixed header -->
<div class="h-20"></div>

// src/components/layout/Header.tsx
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { Menu, X } from "lucide-react";

const navLinks = [
  { label: "Work", href: "/work" },
  { label: "Offers", href: "/#offers" },
  { label: "How it works", href: "/#how-it-works" },
  { label: "About", href: "/#about" },
  { label: "Resources", href: "/resources" },
  { label: "Contact", href: "/#contact" },
];

const Header = () => {
  const [isOpen, setIsOpen] = useState(false);
  const location = useLocation();

  const handleNavClick = (href: string) => {
    setIsOpen(false);
    if (href.startsWith("/#")) {
      if (location.pathname !== "/") {
        window.location.href = href;
      } else {
        const id = href.replace("/#", "");
        document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
      }
    }
  };

  return (
    <header className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-xl border-b border-border">
      <div className="section-container">
        <div className="flex items-center justify-between h-16 lg:h-20">
          {/* Logo */}
          <Link to="/" className="flex items-center gap-3">
            <img
              src="/logo.webp"
              alt="AS"
              className="w-10 h-10 rounded-full"
            />
          </Link>

          {/* Desktop Navigation */}
          <nav className="hidden lg:flex items-center gap-8">
            {navLinks.map((link) => (
              link.href.startsWith("/#") ? (
                <button
                  key={link.label}
                  onClick={() => handleNavClick(link.href)}
                  className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
                >
                  {link.label}
                </button>
              ) : (
                <Link
                  key={link.label}
                  to={link.href}
                  className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
                >
                  {link.label}
                </Link>
              )
            ))}
          </nav>

          {/* CTA Button */}
          <div className="hidden lg:block">
            <a
              href="https://calendly.com/datable-as/llm-stack-sprint-intro-call"
              target="_blank"
              rel="noopener noreferrer"
              className="btn-primary text-sm"
            >
              Book 15-min Call
            </a>
          </div>

          {/* Mobile Menu Button */}
          <button
            onClick={() => setIsOpen(!isOpen)}
            className="lg:hidden p-2 text-foreground"
            aria-label="Toggle menu"
          >
            {isOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        </div>

        {/* Mobile Navigation */}
        {isOpen && (
          <div className="lg:hidden py-4 border-t border-border">
            <nav className="flex flex-col gap-4">
              {navLinks.map((link) => (
                link.href.startsWith("/#") ? (
                  <button
                    key={link.label}
                    onClick={() => handleNavClick(link.href)}
                    className="text-left text-base font-medium text-muted-foreground hover:text-foreground transition-colors py-2"
                  >
                    {link.label}
                  </button>
                ) : (
                  <Link
                    key={link.label}
                    to={link.href}
                    onClick={() => setIsOpen(false)}
                    className="text-base font-medium text-muted-foreground hover:text-foreground transition-colors py-2"
                  >
                    {link.label}
                  </Link>
                )
              ))}
              <a
                href="https://calendly.com/datable-as/llm-stack-sprint-intro-call"
                target="_blank"
                rel="noopener noreferrer"
                className="btn-primary text-center mt-2"
              >
                Book 15-min Call
              </a>
            </nav>
          </div>
        )}
      </div>
    </header>
  );
};

export default Header;
