// src/lib/components/Hero.svelte
<script>
	import { onMount } from 'svelte';

	let visible = false;
	onMount(() => {
		visible = true;
	});
</script>

<section class="min-h-[90vh] flex items-center justify-center section-alt relative overflow-hidden">
	<div class="absolute inset-0 bg-grid dark:bg-grid-dark opacity-30"></div>
	
	<div class="max-w-4xl px-6 py-20 text-center relative">
		<div class="space-y-6" class:animate-slide-up={visible}>
				<h1
						class="text-3xl sm:text-4xl md:text-5xl lg:text-6xl
						 font-bold heading leading-tight break-words tracking-wide"
				>
					<span class="text-gradient">
						Get your AI / LLM stack
						<br class="hidden sm:block" />
						production‑ready in 10 days
					</span>
				</h1>

				<p class="text-xl subheading max-w-2xl mx-auto">
						I stabilise, scale and harden ML & LLM systems for teams like Mentalyc, Einbliq,
						AIREV and the EU Commission &mdash; fully remote.
				</p>
			<div class="flex flex-col sm:flex-row gap-4 justify-center items-center mt-8">
				<a href="#contact" class="btn-primary group">
					Book a 15‑minute diagnostic call
					<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 transition-transform group-hover:translate-x-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"></path>
					</svg>
				</a>
				<a
						href="https://www.notion.so/LLM-Stack-Diagnostic-Sprint-1be4e72a76e7808ca8ced73e87c0b211"
						target="_blank" rel="noopener noreferrer"
						class="btn-primary bg-white/10 hover:bg-white/20 text-gray-800 dark:text-white"
				>
						Sprint Details
				</a>
			</div>
		</div>

		<!-- Decorative Elements -->
		<div class="absolute top-1/2 left-0 -translate-y-1/2 w-64 h-64 bg-primary-500/10 rounded-full blur-3xl"></div>
		<div class="absolute top-1/2 right-0 -translate-y-1/2 w-64 h-64 bg-secondary-500/10 rounded-full blur-3xl"></div>
	</div>
</section>

// src/components/home/Hero.tsx
import { ArrowRight, Mail } from "lucide-react";
import { Link } from "react-router-dom";

const proofMetrics = [
  "86% cost reduction",
  "88% latency improvement",
  "90% less alert triage",
  "30% revenue impact",
  "1M+ devices modeled",
  "p95 < 1s at scale",
];

const clientLogos = [
  { src: "/logos/airev-sm.webp", alt: "AIREV" },
  { src: "/logos/mentalyc-sm.webp", alt: "Mentalyc" },
  { src: "/logos/einbliq-dark-sm.webp", alt: "Einbliq" },
  { src: "/logos/yumio-sm.webp", alt: "Yumio" },
  { src: "/logos/ec-sm.webp", alt: "European Commission" },
];

const Hero = () => {
  return (
    <section className="py-20 lg:py-32 relative overflow-hidden">
      {/* Background glow effect */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-primary/5 rounded-full blur-3xl pointer-events-none" />
      
      <div className="section-container relative">
        <div className="max-w-4xl mx-auto text-center">
          {/* Eyebrow */}
          <span className="inline-block px-4 py-2 mb-6 text-sm font-medium text-primary bg-primary/10 rounded-full border border-primary/20">
            Production AI & Data Systems Architect
          </span>

          {/* Name */}
          <p className="text-lg text-muted-foreground mb-4">
            Andreas Sapountzis
          </p>

          {/* Headline */}
          <h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-bold text-foreground mb-6 text-balance">
            End-to-end AI systems engineering — built for production.
          </h1>

          {/* Subheadline */}
          <p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-3xl mx-auto text-balance">
            I design and ship AI systems under real constraints: cost, latency, privacy, and reliability. Best for 0→1 delivery and high-stakes rescues.
          </p>

          {/* CTAs */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-6">
            <a
              href="https://calendly.com/datable-as/llm-stack-sprint-intro-call"
              target="_blank"
              rel="noopener noreferrer"
              className="btn-primary group"
            >
              Book 15-min Call
              <ArrowRight size={18} className="ml-2 group-hover:translate-x-1 transition-transform" />
            </a>
            <Link to="/brief" className="btn-secondary">
              Send a 2-minute Brief
            </Link>
          </div>

          {/* Tertiary CTA */}
          <Link
            to="/resources/ai-systems-launch-checklist"
            className="inline-block text-sm text-muted-foreground hover:text-primary transition-colors mb-4"
            style={{ animationDelay: "0.5s" }}
          >
            Get the AI Systems Launch Checklist (free PDF) →
          </Link>

          {/* Email chip */}
          <a
            href="mailto:sapountzis.andreas@gmail.com"
            className="inline-flex items-center gap-2 px-4 py-2 text-sm text-muted-foreground hover:text-foreground bg-secondary/50 rounded-full border border-border hover:border-primary/30 transition-all"
            style={{ animationDelay: "0.6s" }}
          >
            <Mail size={16} />
            sapountzis.andreas@gmail.com
          </a>
        </div>

        {/* Proof bar */}
        <div className="mt-16">
          <div className="flex flex-wrap justify-center gap-4 md:gap-6">
            {proofMetrics.map((metric) => (
              <div
                key={metric}
                className="px-4 py-2 text-sm font-medium text-foreground bg-secondary/50 rounded-lg border border-border"
              >
                {metric}
              </div>
            ))}
          </div>
        </div>

        {/* Client logos */}
        <div className="mt-16">
          <p className="text-sm text-muted-foreground text-center mb-6">Worked with</p>
          <div className="flex flex-wrap justify-center items-center gap-8 md:gap-12">
            {clientLogos.map((logo) => (
              <img
                key={logo.alt}
                src={logo.src}
                alt={logo.alt}
                className="h-8 md:h-10 opacity-60 hover:opacity-100 transition-opacity grayscale hover:grayscale-0"
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
